### ISSUE TITLE
Massive page does not display correctly

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/digapp-ht#12]
http://localhost:5009/email.html?value=http://dig.isi.edu/ht/data/email/bellaamourcompanions@safeoffice.com&field=_id

**Comment by szeke** [comment]
The page displays correctly, but uglily. The map is there, but the component is super tall and the map is in the middle. Need to talk to David about the resizing of the components.

**Comment by dkapoor** [comment]
The page looks fine now after the layout changes. Should we close this now @szeke?

**Comment by szeke** [comment]
Works correctly now
