### ISSUE TITLE
Define title for seller page

### ISSUE THREAD

**Issue by szeke** [usc-isi-i2/digapp-ht#6]
Seller pages need a title. Seller objects have no name property, so we need to construct a title for the seller entity page from the data. Sellers have phone numbers and emails. One possibility for the title is

"Seller: phone1, phone2, ..., email1, email2, ..."

Show up to two phone numbers and ... if there are more, same with emails.

Perhaps the way to do this in polymer is to define a SellerNameFormattter, similar to PhoneFormatter, the difference would be that the PhoneFormatter takes a string as input, and the SellerFormatter needs the whole object.

**Comment by saggu** [comment]
Completed.
