### ISSUE TITLE
JS Error in index page

### ISSUE THREAD

**Issue by saggu** [usc-isi-i2/digapp-ht#7]
expected array for `items`, found Hi, My name is Jessica

I'm sexy, fun & ready to get WILD

To replicate:
1. search for jessica
2. filter on any facet
Look in the console

**Comment by szeke** [comment]
Is this still a problem?

**Comment by saggu** [comment]
Yes, I will report this to NC.

**Comment by szeke** [comment]
Close?

**Comment by saggu** [comment]
This has been resolved, regarding the facets
